name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/837056944608/locations/global/workloadIdentityPools/theovenssecret/providers/github-provider'
          service_account: 'github-action-1162900851@project-4eb9ff52-43b8-4ee6-a16.iam.gserviceaccount.com'
          token_format: 'access_token'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Install dependencies
        run: npm install
        
      - name: Build Next.js
        run: npm run build

      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          firebase deploy --project=the-ovens-secret
        env:
          FIREBASE_TOKEN: ${{ steps.auth.outputs.credentials_file_path }}

      
